package lt.vu.usecases.mybatis.model;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.VIN
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    private String vin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.BUILT
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    private Date built;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.COLOR
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    private Integer ownerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.VIN
     *
     * @return the value of PUBLIC.CAR.VIN
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.VIN
     *
     * @param vin the value for PUBLIC.CAR.VIN
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public void setVin(String vin) {
        this.vin = vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.BUILT
     *
     * @return the value of PUBLIC.CAR.BUILT
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public Date getBuilt() {
        return built;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.BUILT
     *
     * @param built the value for PUBLIC.CAR.BUILT
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public void setBuilt(Date built) {
        this.built = built;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.COLOR
     *
     * @return the value of PUBLIC.CAR.COLOR
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.COLOR
     *
     * @param color the value for PUBLIC.CAR.COLOR
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.OWNER_ID
     *
     * @return the value of PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.OWNER_ID
     *
     * @param ownerId the value for PUBLIC.CAR.OWNER_ID
     *
     * @mbg.generated Tue Apr 23 22:02:48 EEST 2019
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }
}