package lt.vu.usecases.mybatis.model;

public class StudentCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @param studentId the value for PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @param courseId the value for PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}