CREATE TABLE IF NOT EXISTS INSURANCE
(
	ID INTEGER NOT NULL IDENTITY,
	DATE_START DATE,
	DATE_END   DATE,
	PRICE      DECIMAL(20, 2),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS OWNER
(
  ID INTEGER NOT NULL IDENTITY,
	FIRST_NAME       VARCHAR(50),
  LAST_NAME        VARCHAR(50),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CAR
(
  ID INTEGER NOT NULL IDENTITY,
  VIN      VARCHAR(50),
  BUILT    DATE NOT NULL,
  COLOR    VARCHAR(50),
  OWNER_ID INTEGER,
  FOREIGN KEY (OWNER_ID) REFERENCES OWNER (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS INSURANCE_CAR
(
  INSURANCE_ID INTEGER,
  CAR_ID       INTEGER,
  PRIMARY KEY (INSURANCE_ID, CAR_ID),
  FOREIGN KEY (INSURANCE_ID) REFERENCES INSURANCE (ID),
  FOREIGN KEY(CAR_ID) REFERENCES CAR (ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNT
(
  ID INTEGER NOT NULL IDENTITY,
  USER_NAME        VARCHAR(128) NOT NULL UNIQUE,
  PASSWORD_DIGEST  VARCHAR(256) NOT NULL,
  FIRST_NAME       VARCHAR(20),
  LAST_NAME        VARCHAR(20),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNT_GROUP
(
  ACCOUNT_ID       INTEGER,
  GROUP_NAME       VARCHAR(128),
  PRIMARY KEY (ACCOUNT_ID, GROUP_NAME),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
);
